// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mefs.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetInfo_NetType int32

const (
	NetInfo_Unknown NetInfo_NetType = 0
	NetInfo_P2PAddr NetInfo_NetType = 1
)

var NetInfo_NetType_name = map[int32]string{
	0: "Unknown",
	1: "P2PAddr",
}

var NetInfo_NetType_value = map[string]int32{
	"Unknown": 0,
	"P2PAddr": 1,
}

func (x NetInfo_NetType) String() string {
	return proto.EnumName(NetInfo_NetType_name, int32(x))
}

func (NetInfo_NetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{0, 0}
}

type RoleInfo_Type int32

const (
	RoleInfo_Unknown  RoleInfo_Type = 0
	RoleInfo_User     RoleInfo_Type = 1
	RoleInfo_Provider RoleInfo_Type = 2
	RoleInfo_Keeper   RoleInfo_Type = 3
)

var RoleInfo_Type_name = map[int32]string{
	0: "Unknown",
	1: "User",
	2: "Provider",
	3: "Keeper",
}

var RoleInfo_Type_value = map[string]int32{
	"Unknown":  0,
	"User":     1,
	"Provider": 2,
	"Keeper":   3,
}

func (x RoleInfo_Type) String() string {
	return proto.EnumName(RoleInfo_Type_name, int32(x))
}

func (RoleInfo_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{1, 0}
}

// register on data chain
// key: 'NetInfoKey'/RoleID;
type NetInfo struct {
	Type                 NetInfo_NetType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.NetInfo_NetType" json:"type,omitempty"`
	NetID                []byte          `protobuf:"bytes,2,opt,name=netID,proto3" json:"netID,omitempty"`
	Addr                 []byte          `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NetInfo) Reset()         { *m = NetInfo{} }
func (m *NetInfo) String() string { return proto.CompactTextString(m) }
func (*NetInfo) ProtoMessage()    {}
func (*NetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{0}
}
func (m *NetInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfo.Merge(m, src)
}
func (m *NetInfo) XXX_Size() int {
	return m.Size()
}
func (m *NetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfo proto.InternalMessageInfo

func (m *NetInfo) GetType() NetInfo_NetType {
	if m != nil {
		return m.Type
	}
	return NetInfo_Unknown
}

func (m *NetInfo) GetNetID() []byte {
	if m != nil {
		return m.NetID
	}
	return nil
}

func (m *NetInfo) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

// key: 'RoleInfoKey'/'RoleType'/RoleID
type RoleInfo struct {
	Type                 RoleInfo_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.RoleInfo_Type" json:"type,omitempty"`
	RoleID               uint64        `protobuf:"varint,2,opt,name=roleID,proto3" json:"roleID,omitempty"`
	GroupID              uint64        `protobuf:"varint,3,opt,name=groupID,proto3" json:"groupID,omitempty"`
	ChainVerifyKey       []byte        `protobuf:"bytes,4,opt,name=chainVerifyKey,proto3" json:"chainVerifyKey,omitempty"`
	BlsVerifyKey         []byte        `protobuf:"bytes,5,opt,name=blsVerifyKey,proto3" json:"blsVerifyKey,omitempty"`
	Extra                []byte        `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	Desc                 []byte        `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	State                string        `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{1}
}
func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return m.Size()
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetType() RoleInfo_Type {
	if m != nil {
		return m.Type
	}
	return RoleInfo_Unknown
}

func (m *RoleInfo) GetRoleID() uint64 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *RoleInfo) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *RoleInfo) GetChainVerifyKey() []byte {
	if m != nil {
		return m.ChainVerifyKey
	}
	return nil
}

func (m *RoleInfo) GetBlsVerifyKey() []byte {
	if m != nil {
		return m.BlsVerifyKey
	}
	return nil
}

func (m *RoleInfo) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *RoleInfo) GetDesc() []byte {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *RoleInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.NetInfo_NetType", NetInfo_NetType_name, NetInfo_NetType_value)
	proto.RegisterEnum("pb.RoleInfo_Type", RoleInfo_Type_name, RoleInfo_Type_value)
	proto.RegisterType((*NetInfo)(nil), "pb.NetInfo")
	proto.RegisterType((*RoleInfo)(nil), "pb.RoleInfo")
}

func init() { proto.RegisterFile("mefs.proto", fileDescriptor_2b3c77393cf6fe78) }

var fileDescriptor_2b3c77393cf6fe78 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0xd4, 0x4d, 0xca, 0x6d, 0x55, 0x05, 0x83, 0x90, 0xa7, 0xa8, 0x0a, 0x02, 0x3a,
	0x65, 0x28, 0x03, 0x33, 0xa8, 0x4b, 0x55, 0x09, 0x55, 0x11, 0x65, 0x4f, 0x9a, 0x5b, 0xa8, 0x28,
	0xb1, 0xe5, 0x98, 0x9f, 0x8c, 0xbc, 0x05, 0x8f, 0xc0, 0xa3, 0x30, 0xf2, 0x08, 0x28, 0xbc, 0x08,
	0xb2, 0xd3, 0x0a, 0x0a, 0x93, 0xef, 0x39, 0xf7, 0xd8, 0xfa, 0x74, 0x0c, 0x70, 0x8f, 0x8b, 0x22,
	0x92, 0x4a, 0x68, 0xc1, 0x1c, 0x99, 0x86, 0x2f, 0x04, 0xbc, 0x4b, 0xd4, 0xe3, 0x7c, 0x21, 0xd8,
	0x09, 0x50, 0x5d, 0x4a, 0xe4, 0xa4, 0x4f, 0x06, 0xbd, 0xe1, 0x5e, 0x24, 0xd3, 0x68, 0xbd, 0x32,
	0xe7, 0x55, 0x29, 0x31, 0xb6, 0x01, 0xb6, 0x0f, 0xad, 0x1c, 0xf5, 0x78, 0xc4, 0x9d, 0x3e, 0x19,
	0x74, 0xe3, 0x5a, 0x30, 0x06, 0x34, 0xc9, 0x32, 0xc5, 0x9b, 0xd6, 0xb4, 0x73, 0x78, 0x68, 0x5f,
	0x37, 0x57, 0x59, 0x07, 0xbc, 0x59, 0x7e, 0x97, 0x8b, 0xa7, 0xdc, 0x6f, 0x18, 0x31, 0x1d, 0x4e,
	0xcf, 0xb3, 0x4c, 0xf9, 0x24, 0x7c, 0x73, 0xa0, 0x1d, 0x8b, 0x15, 0x5a, 0x88, 0xa3, 0x2d, 0x88,
	0x5d, 0x03, 0xb1, 0xd9, 0x45, 0xbf, 0x10, 0x0e, 0xc0, 0x55, 0xc6, 0xae, 0x19, 0x68, 0xbc, 0x56,
	0x8c, 0x83, 0x77, 0xa3, 0xc4, 0x83, 0x1c, 0x8f, 0x2c, 0x07, 0x8d, 0x37, 0x92, 0x1d, 0x43, 0x6f,
	0x7e, 0x9b, 0x2c, 0xf3, 0x6b, 0x54, 0xcb, 0x45, 0x39, 0xc1, 0x92, 0x53, 0x0b, 0xfa, 0xc7, 0x65,
	0x21, 0x74, 0xd3, 0x55, 0xf1, 0x93, 0x6a, 0xd9, 0xd4, 0x96, 0x67, 0x0a, 0xc0, 0x67, 0xad, 0x12,
	0xee, 0xd6, 0x05, 0x58, 0x61, 0x0a, 0xc8, 0xb0, 0x98, 0x73, 0xaf, 0x2e, 0xc0, 0xcc, 0x26, 0x59,
	0xe8, 0x44, 0x23, 0xef, 0xf4, 0xc9, 0x60, 0x27, 0xae, 0x45, 0x78, 0x06, 0xf4, 0x7f, 0x27, 0x6d,
	0xa0, 0xb3, 0x02, 0x95, 0x4f, 0x58, 0x17, 0xda, 0x53, 0x25, 0x1e, 0x97, 0x19, 0x2a, 0xdf, 0x61,
	0x00, 0xee, 0x04, 0x51, 0xa2, 0xf2, 0x9b, 0x17, 0xfe, 0x7b, 0x15, 0x90, 0x8f, 0x2a, 0x20, 0x9f,
	0x55, 0x40, 0x5e, 0xbf, 0x82, 0x46, 0xea, 0xda, 0xbf, 0x3c, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0xed, 0x44, 0x08, 0x90, 0xd9, 0x01, 0x00, 0x00,
}

func (m *NetInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintMefs(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NetID) > 0 {
		i -= len(m.NetID)
		copy(dAtA[i:], m.NetID)
		i = encodeVarintMefs(dAtA, i, uint64(len(m.NetID)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintMefs(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RoleInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoleInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RoleInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintMefs(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Desc) > 0 {
		i -= len(m.Desc)
		copy(dAtA[i:], m.Desc)
		i = encodeVarintMefs(dAtA, i, uint64(len(m.Desc)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Extra) > 0 {
		i -= len(m.Extra)
		copy(dAtA[i:], m.Extra)
		i = encodeVarintMefs(dAtA, i, uint64(len(m.Extra)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BlsVerifyKey) > 0 {
		i -= len(m.BlsVerifyKey)
		copy(dAtA[i:], m.BlsVerifyKey)
		i = encodeVarintMefs(dAtA, i, uint64(len(m.BlsVerifyKey)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ChainVerifyKey) > 0 {
		i -= len(m.ChainVerifyKey)
		copy(dAtA[i:], m.ChainVerifyKey)
		i = encodeVarintMefs(dAtA, i, uint64(len(m.ChainVerifyKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.GroupID != 0 {
		i = encodeVarintMefs(dAtA, i, uint64(m.GroupID))
		i--
		dAtA[i] = 0x18
	}
	if m.RoleID != 0 {
		i = encodeVarintMefs(dAtA, i, uint64(m.RoleID))
		i--
		dAtA[i] = 0x10
	}
	if m.Type != 0 {
		i = encodeVarintMefs(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMefs(dAtA []byte, offset int, v uint64) int {
	offset -= sovMefs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NetInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovMefs(uint64(m.Type))
	}
	l = len(m.NetID)
	if l > 0 {
		n += 1 + l + sovMefs(uint64(l))
	}
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovMefs(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RoleInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovMefs(uint64(m.Type))
	}
	if m.RoleID != 0 {
		n += 1 + sovMefs(uint64(m.RoleID))
	}
	if m.GroupID != 0 {
		n += 1 + sovMefs(uint64(m.GroupID))
	}
	l = len(m.ChainVerifyKey)
	if l > 0 {
		n += 1 + l + sovMefs(uint64(l))
	}
	l = len(m.BlsVerifyKey)
	if l > 0 {
		n += 1 + l + sovMefs(uint64(l))
	}
	l = len(m.Extra)
	if l > 0 {
		n += 1 + l + sovMefs(uint64(l))
	}
	l = len(m.Desc)
	if l > 0 {
		n += 1 + l + sovMefs(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovMefs(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMefs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMefs(x uint64) (n int) {
	return sovMefs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NetInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMefs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= NetInfo_NetType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMefs
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMefs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetID = append(m.NetID[:0], dAtA[iNdEx:postIndex]...)
			if m.NetID == nil {
				m.NetID = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMefs
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMefs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMefs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMefs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RoleInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMefs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoleInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoleInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= RoleInfo_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleID", wireType)
			}
			m.RoleID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoleID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			m.GroupID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainVerifyKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMefs
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMefs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainVerifyKey = append(m.ChainVerifyKey[:0], dAtA[iNdEx:postIndex]...)
			if m.ChainVerifyKey == nil {
				m.ChainVerifyKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsVerifyKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMefs
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMefs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlsVerifyKey = append(m.BlsVerifyKey[:0], dAtA[iNdEx:postIndex]...)
			if m.BlsVerifyKey == nil {
				m.BlsVerifyKey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extra", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMefs
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMefs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extra = append(m.Extra[:0], dAtA[iNdEx:postIndex]...)
			if m.Extra == nil {
				m.Extra = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Desc", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMefs
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMefs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Desc = append(m.Desc[:0], dAtA[iNdEx:postIndex]...)
			if m.Desc == nil {
				m.Desc = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMefs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMefs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMefs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMefs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMefs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMefs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMefs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMefs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMefs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMefs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMefs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMefs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMefs = fmt.Errorf("proto: unexpected end of group")
)
